import json
from core.agents.base import Agent
from core.services.agent_manager import AgentManager

class OrchestratorAgent(Agent):
    def __init__(self, agent_manager: AgentManager, name="OrchestratorAgent"):
        super().__init__(name)
        self.agent_manager = agent_manager
        self.register_skill("process_natural_language_command", self.process_natural_language_command)

    def process_natural_language_command(self, command: str):
        """
        Processes a natural language command by using the LLMAgent to create a task plan,
        and then executes the plan.
        """
        print(f"'{self.name}' received natural language command: {command}")

        llm_agent = self._find_agent_by_class("LLMAgent")
        if not llm_agent:
            print("Error: LLMAgent not found.")
            return

        # Create a prompt for the LLM to generate a task plan
        prompt = self._create_task_planning_prompt(command)

        # Get the task plan from the LLM
        task_plan_str = llm_agent.execute_task("reason", prompt)
        if not task_plan_str:
            print("Error: Could not get a task plan from the LLMAgent.")
            return

        # Execute the task plan
        self._execute_task_plan(task_plan_str)

    def _create_task_planning_prompt(self, command: str) -> str:
        """
        Creates a prompt for the LLM to generate a task plan from a natural language command.
        """
        # Get a list of available agents and their skills
        available_skills = self._get_available_skills()

        prompt = f"""
        You are an orchestrator agent. Your job is to take a natural language command and break it down into a series of tasks for other agents to execute.
        The available agents and their skills are:
        {available_skills}

        The user's command is: "{command}"

        Please provide a JSON-formatted list of tasks to execute. Each task should have the following format:
        {{
            "task_type": "skill_name",
            "args": ["arg1", "arg2"],
            "kwargs": {{"kwarg1": "value1"}}
        }}

        For example, if the command is "study the file 'main.py'", the output should be:
        [
            {{
                "task_type": "study_file",
                "args": ["main.py"],
                "kwargs": {{}}
            }}
        ]
        """
        return prompt

    def _get_available_skills(self) -> str:
        """
        Gets a string representation of the available agents and their skills.
        """
        skill_info = []
        for agent in self.agent_manager.agents.values():
            if agent.name != "OrchestratorAgent":
                skills = ", ".join(agent.skills.keys())
                skill_info.append(f"- Agent '{agent.name}': {skills}")
        return "\n".join(skill_info)

    def _execute_task_plan(self, task_plan_str: str):
        """
        Executes a task plan generated by the LLM.
        """
        try:
            task_plan = json.loads(task_plan_str)
        except json.JSONDecodeError:
            print(f"Error: Invalid JSON in task plan: {task_plan_str}")
            return

        for task in task_plan:
            task_type = task.get("task_type")
            args = task.get("args", [])
            kwargs = task.get("kwargs", {})

            target_agent = self._find_agent_for_task(task_type)
            if target_agent:
                print(f"Executing task '{task_type}' on agent '{target_agent.name}'")
                target_agent.execute_task(task_type, *args, **kwargs)
            else:
                print(f"Warning: No agent found for task type '{task_type}'")

    def _find_agent_for_task(self, task_type: str) -> Agent:
        """
        Finds an agent in the agent manager that can handle the given task type.
        """
        for agent in self.agent_manager.agents.values():
            if task_type in agent.skills:
                return agent
        return None

    def _find_agent_by_class(self, class_name: str) -> Agent:
        """
        Finds an agent in the agent manager by its class name.
        """
        for agent in self.agent_manager.agents.values():
            if agent.__class__.__name__ == class_name:
                return agent
        return None
